summary: Form Status for application/html
details:
  - description: Detailed process form responses flows in case if mime type is application/html
    mermaid: >-
      sequenceDiagram
        participant Borrower Platform (BAP)
        participant Lender Platform(BPP)
        participant Lender Form Service
        Lender Platform(BPP)->>Borrower Platform (BAP):on_select
        Borrower Platform (BAP)-->>Lender Platform(BPP): ACK 
        Borrower Platform (BAP)->>Lender Form Service: Get Form
        Lender Form Service-->>Borrower Platform (BAP): Form Received
        Borrower Platform (BAP)->>Lender Form Service: Form Submission
        Lender Form Service-->>Borrower Platform (BAP): Submission ID 
        Lender Platform(BPP)->> Borrower Platform (BAP): on_status
        Borrower Platform (BAP)-->>Lender Platform(BPP): ACK
        Borrower Platform (BAP)->>Lender Platform(BPP): status
        Lender Platform(BPP)-->>Borrower Platform (BAP): ACK
        Lender Platform(BPP)->> Borrower Platform (BAP): on_status
        Borrower Platform (BAP)-->>Lender Platform(BPP): ACK 
        Borrower Platform (BAP)->>Lender Platform(BPP): init         
references: if any
steps:
  - summary: The provider offers the required form for the chosen personal loan service.
    api: on_select
    details:
      - description: The provider platform responds with detailed information and the necessary application form for the selected personal loan service.
        mermaid: >-
          sequenceDiagram
            participant Borrower Platform (BAP)
            participant Lender Platform(BPP)
            participant Lender Form Service
            rect rgb(191, 223, 255)
            Lender Platform(BPP)->>Borrower Platform (BAP):on_select
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK 
            end
            Borrower Platform (BAP)->>Lender Form Service: Get Form
            Lender Form Service-->>Borrower Platform (BAP): Form Received
            Borrower Platform (BAP)->>Lender Form Service: Form Submission
            Lender Form Service-->>Borrower Platform (BAP): Submission ID 
            Lender Platform(BPP)->> Borrower Platform (BAP): on_status
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK
         
    reference: if any
    example:
      value: 
        $ref: "../../examples/personal-loans/on_select/on_select-request-appilication-html.yaml"
  - summary: Consumer platform fetches the EKYC form
    api: form
    details:
      - description: Consumer platform fetches the EKYC Details form from the Provider platform using the link provided in the previous step
        mermaid: >-
          sequenceDiagram
            participant Borrower Platform (BAP)
            participant Lender Platform(BPP)
            participant Lender Form Service
            Lender Platform(BPP)->>Borrower Platform (BAP):on_select
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK 
            rect rgb(191, 223, 255)
            Borrower Platform (BAP)->>Lender Form Service: Get Form
            Lender Form Service-->>Borrower Platform (BAP): Form Received
            Borrower Platform (BAP)->>Lender Form Service: Form Submission
            Lender Form Service-->>Borrower Platform (BAP): Submission ID 
            end
            Lender Platform(BPP)->> Borrower Platform (BAP): on_status
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK
         
    reference: if any
    example:
      value: 
        $ref: "../../examples/personal-loans/forms/ekyc-type-application.html"
  - summary: Insurer provides the Buyer with latest update of form status .
    api: on_status
    details:
      - description: Insurer provides the Buyer with latest update of form status from unsolicited call
        mermaid: >-
          sequenceDiagram
            participant Borrower Platform (BAP)
            participant Lender Platform(BPP)
            participant Lender Form Service
            Lender Platform(BPP)->>Borrower Platform (BAP):on_select
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK 
            Borrower Platform (BAP)->>Lender Form Service: Get Form
            Lender Form Service-->>Borrower Platform (BAP): Form Received
            Borrower Platform (BAP)->>Lender Form Service: Form Submission
            Lender Form Service-->>Borrower Platform (BAP): Submission ID
            rect rgb(191, 223, 255) 
            Lender Platform(BPP)->> Borrower Platform (BAP): on_status
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK
            end
         
    reference: if any
    example:
      value: 
        $ref: "../../examples/personal-loans/on_status/on_status-form-submitted.yaml"
  - summary: Buyer platform request the latest form status updates.
    api: status
    details:
      - description: Buyer platform request the latest form status updates with the formID
        mermaid: >-
          sequenceDiagram
            title  Selection
            participant Borrower Platform (BAP)
            participant Lender Platform(BPP)
            participant Lender Form Service
            rect rgb(191, 223, 255)
            Borrower Platform (BAP)->>Lender Platform(BPP): status
            Lender Platform(BPP)-->>Borrower Platform (BAP): ACK
            end
            Lender Platform(BPP)->> Borrower Platform (BAP): on_status
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK
    reference: if any
    example:
      value: 
        $ref: "../../examples/personal-loans/status/status-request.yaml"      
  - summary: Insurer provides the Buyer with latest update of form status(Form Processing).
    api: on_status
    details:
      - description: Insurer provides the Buyer with latest update of the form status
        mermaid: >-
          sequenceDiagram
            title  Selection
            participant Borrower Platform (BAP)
            participant Lender Platform(BPP)
            participant Lender Form Service
            
            Borrower Platform (BAP)->>Lender Platform(BPP): status
            Lender Platform(BPP)-->>Borrower Platform (BAP): ACK
            rect rgb(191, 223, 255)
            Lender Platform(BPP)->> Borrower Platform (BAP): on_status
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK
            end
    reference: if any
    example:
      value: 
        $ref: "../../examples/personal-loans/on_status/on_status-form-processing.yaml"      


  - summary: Buyer platform request the latest form status updates.
    api: status
    details:
      - description: Buyer platform request the latest form status updates with the formID
        mermaid: >-
          sequenceDiagram
            title  Selection
            participant Borrower Platform (BAP)
            participant Lender Platform(BPP)
            participant Lender Form Service
            rect rgb(191, 223, 255)
            Borrower Platform (BAP)->>Lender Platform(BPP): status
            Lender Platform(BPP)-->>Borrower Platform (BAP): ACK
            end
            Lender Platform(BPP)->> Borrower Platform (BAP): on_status
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK
            Borrower Platform (BAP)->>Lender Platform(BPP): init
    reference: if any
    example:
      value: 
        $ref: "../../examples/personal-loans/status/status-request.yaml"      
  - summary: Insurer provides the Buyer with latest update of form status(Form Completed) .
    api: on_status
    details:
      - description: Insurer provides the Buyer with latest update of the form status
        mermaid: >-
          sequenceDiagram
            title  Selection
            participant Borrower Platform (BAP)
            participant Lender Platform(BPP)
            participant Lender Form Service
            Borrower Platform (BAP)->>Lender Platform(BPP): status
            Lender Platform(BPP)-->>Borrower Platform (BAP): ACK
            rect rgb(191, 223, 255)
            Lender Platform(BPP)->> Borrower Platform (BAP): on_status
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK
            end
            Borrower Platform (BAP)->>Lender Platform(BPP): init
    reference: if any
    example:
      value: 
        $ref: "../../examples/personal-loans/on_status/on_status-form-completed.yaml"    
  - summary: The consumer platform initiates the health insurace request.
    api: init
    details:
      - description: Consumer platform initiates purchase of a specific health insurance plan that suits their customer needs and links the EKYC submission details with it.
        mermaid: >-
          sequenceDiagram
            title  Selection
            participant Borrower Platform (BAP)
            participant Lender Platform(BPP)
            participant Lender Form Service
            Borrower Platform (BAP)->>Lender Platform(BPP): status
            Lender Platform(BPP)-->>Borrower Platform (BAP): ACK
            Lender Platform(BPP)->> Borrower Platform (BAP): on_status
            Borrower Platform (BAP)-->>Lender Platform(BPP): ACK
            rect rgb(191, 223, 255)
            Borrower Platform (BAP)->>Lender Platform(BPP): init
            end
    reference: if any
    example: 
      value:
        $ref: "../../examples/personal-loans/init/init-request-kyc-approved.yaml"
  